"""Init table

Revision ID: e033ed3b820f
Revises:
Create Date: 2022-06-04 10:46:23.362665

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "e033ed3b820f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchangerate",
        sa.Column("currency", sa.Enum("USD", "EUR", "CHF", "JPY", "PLN", name="currency"), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("rate", sa.Numeric(), nullable=True),
        sa.PrimaryKeyConstraint("rate_date", "currency"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchangerate")
    # ### end Alembic commands ###
